### ISSUE TITLE
Subpackages are to tightly linked

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/airflow-feedstock#145]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

In #142 you switched to `exact` pinning of the subpackages. The noarch subpackages are then pinned against a specific python version, for example [airflow-with-ldap-2.10.4-hd8ed1ab_1.conda](https://anaconda.org/conda-forge/airflow-with-ldap/2.10.4/download/noarch/airflow-with-ldap-2.10.4-hd8ed1ab_1.conda) has this rendered requirements section in the recipe:
```yaml
...
requirements:
  build: []
  run:
    - airflow 2.10.4 py39hf3d152e_1
    - ldap3 >=2.5.1
    - python >=3.9,<3.13
    - python-ldap
...
```
